"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.platform3 = exports.platform2 = exports.platform1 = void 0;
//-- Importar clases
var platform_1 = require("./platform");
//-- Pruebas
var platform1 = new platform_1.Platform("Electronic Arts", 1982, "Electronic Arts Inc.", 45625874421, 1, true, 1080, true, platform_1.StorageDevice.cartridge, "Orange");
exports.platform1 = platform1;
var platform2 = new platform_1.Platform("Steam", 2003, "Valve Corporation", 456851879815498, 2, true, 1080, true, platform_1.StorageDevice.card, "blue");
exports.platform2 = platform2;
var platform3 = new platform_1.Platform("Electronic Arts", 1982, "Electronic Arts Inc.", 45625874421, 1, true, 1080, true, platform_1.StorageDevice.cartridge, "Orange");
exports.platform3 = platform3;
console.log("----------------EQUAL-PLATFORMS-----------------");
console.log("\u00BF platform1 es igual a platform2 ?: ".concat(platform1.equalPlatform(platform2)));
console.log("\u00BF platform1 es igual a platform3 ?: ".concat(platform1.equalPlatform(platform3)));
console.log("----------------------------------------------");
console.log("--------------PRINT-ATTRIBUTES----------------");
console.log("-------platform1-------");
platform1.printAttributes();
console.log("-------platform2-------");
platform2.printAttributes();
console.log("-------platform3-------");
console.log("Los datos actuales de platform3 son iguales que los de platform1: ");
console.log("name = ".concat(platform3.getName()));
console.log("releaseYear = ".concat(platform3.getReleaseYear()));
console.log("company = ".concat(platform3.getCompany()));
console.log("nBits = ".concat(platform3.getNBits()));
console.log("generation = ".concat(platform3.getGeneration()));
console.log("hasHD = ".concat(platform3.getHasHD()));
console.log("hDSize = ".concat(platform3.getHDSize()));
console.log("hasInterntConexion = ".concat(platform3.getHasInterntConexion()));
console.log("storageDevice = ".concat(platform3.getStorageDevice()));
console.log("color = ".concat(platform3.getColor()));
console.log("-------------Cambiando datos...-----------");
platform3.setName("Riot Games");
platform3.setReleaseYear(2006);
platform3.setCompany("Riot Games,Inc.");
platform3.setNBits(48294518945618);
platform3.setGeneration(3);
platform3.setHasHD(true);
platform3.setHDSize(1080);
platform3.setHasInterntConexion(true);
platform3.setStorageDevice(platform_1.StorageDevice.card);
platform3.setColor("Red");
platform3.printAttributes();
console.log("----------------------------------------------");
console.log("-------------------TO-STRING------------------");
console.log("-------platform1-------");
console.log(platform1.toString());
console.log("-------platform2-------");
console.log(platform2.toString());
console.log("-------platform3-------");
console.log(platform3.toString());
console.log("----------------------------------------------");
