"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.persona5 = exports.persona4 = exports.persona3 = exports.persona2 = exports.persona1 = void 0;
//-- Importar clases
var person_1 = require("./person");
var person_2 = require("./person");
//-- Pruebas
var persona1 = new person_1.Person("Cris", "Española", person_2.Profesion.developer, 3);
exports.persona1 = persona1;
var persona2 = new person_1.Person("Manuel", "Española", person_2.Profesion.director, 20);
exports.persona2 = persona2;
var persona3 = new person_1.Person("Mari", "Española", person_2.Profesion.tester, 11);
exports.persona3 = persona3;
var persona4 = new person_1.Person("Oliver", "Española", person_2.Profesion.manager, 7);
exports.persona4 = persona4;
var persona5 = new person_1.Person("Cris", "Española", person_2.Profesion.developer, 3);
exports.persona5 = persona5;
console.log("----------------EQUAL-PERSONS-----------------");
console.log("\u00BF persona1 es igual a persona2 ?: ".concat(persona1.equalPersons(persona2)));
console.log("\u00BF persona1 es igual a persona5 ?: ".concat(persona1.equalPersons(persona5)));
console.log("----------------------------------------------");
console.log("--------------PRINT-ATTRIBUTES----------------");
console.log("-------persona1-------");
persona1.printAttributes();
console.log("-------persona2-------");
persona2.printAttributes();
console.log("-------persona3-------");
persona3.printAttributes();
console.log("-------persona4-------");
persona4.printAttributes();
console.log("-------persona5-------");
console.log("Los datos actuales de persona5 son iguales que los de persona1: ");
console.log("name = ".concat(persona5.getName()));
console.log("nationality = ".concat(persona5.getNationality()));
console.log("profession = ".concat(persona5.getProfession()));
console.log("experienceYears = ".concat(persona5.getExperienceYears()));
console.log("-------------Cambiando datos...-----------");
persona5.setName("Taehyung");
persona5.setNationality("South Korean");
persona5.setProfession(person_2.Profesion.developer);
persona5.setExperienceYears(10);
persona5.printAttributes();
console.log("----------------------------------------------");
console.log("-------------------TO-STRING------------------");
console.log("-------persona1-------");
console.log(persona1.toString());
console.log("-------persona2-------");
console.log(persona2.toString());
console.log("-------persona3-------");
console.log(persona3.toString());
console.log("-------persona4-------");
console.log(persona4.toString());
console.log("-------persona5-------");
console.log(persona5.toString());
console.log("----------------------------------------------");
